import { useEffect } from 'react'
import { useForm } from 'react-hook-form'
import Button from '../Button'
import Input from '../Input'
import Modal from '../Modal'

const blankStudent = { name: '', email: '', password: '', rollNumber: '', registrationNumber: '', semester: '', section: '', session: '', phone: '', status: 'active' }

export default function StudentFormModal({ open, student, onClose, onSubmit, isPending }) {
  const editing = Boolean(student)
  const { register, handleSubmit, reset, formState: { errors } } = useForm({ defaultValues: blankStudent })
  useEffect(() => { reset(student ? { ...student, password: '' } : blankStudent) }, [student, open, reset])
  const submit = (values) => { const payload = { ...values, semester: Number(values.semester) }; if (editing && !payload.password) delete payload.password; onSubmit(payload) }
  return <Modal open={open} onClose={onClose} title={editing ? 'Edit student' : 'Add student'}><form onSubmit={handleSubmit(submit)} noValidate className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Input label="Full name" error={errors.name?.message} {...register('name', { required: 'Name is required', minLength: { value: 2, message: 'Name must be at least 2 characters' } })} /><Input label="Student number" error={errors.rollNumber?.message} {...register('rollNumber', { required: 'Student number is required' })} /></div><div className="grid gap-4 sm:grid-cols-2"><Input label="Email address" type="email" autoComplete="email" error={errors.email?.message} {...register('email', { required: 'Email is required', pattern: { value: /^\S+@\S+\.\S+$/, message: 'Enter a valid email address' } })} /><Input label="Registration number" error={errors.registrationNumber?.message} {...register('registrationNumber', { required: 'Registration number is required' })} /></div><Input label={editing ? 'New password (optional)' : 'Password'} type="password" autoComplete="new-password" error={errors.password?.message} {...register('password', { required: editing ? false : 'Password is required', minLength: { value: 8, message: 'Password must be at least 8 characters' } })} /><div className="grid gap-4 sm:grid-cols-3"><Select label="Semester" error={errors.semester?.message} {...register('semester', { required: 'Semester is required' })}>{Array.from({ length: 20 }, (_, index) => <option key={index + 1} value={index + 1}>Semester {index + 1}</option>)}</Select><Input label="Section" error={errors.section?.message} {...register('section', { required: 'Section is required' })} /><Input label="Session" placeholder="2025-26" error={errors.session?.message} {...register('session', { required: 'Session is required' })} /></div><div className="grid gap-4 sm:grid-cols-2"><Input label="Phone" type="tel" error={errors.phone?.message} {...register('phone', { required: 'Phone is required', pattern: { value: /^[0-9+() -]{7,30}$/, message: 'Enter a valid phone number' } })} /><Select label="Status" {...register('status')}><option value="active">Active</option><option value="inactive">Inactive</option><option value="suspended">Suspended</option></Select></div><div className="flex justify-end gap-3 border-t border-white/10 pt-5"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={isPending}>{isPending ? 'Saving...' : editing ? 'Save changes' : 'Create student'}</Button></div></form></Modal>
}

function Select({ label, error, children, ...props }) { return <label className="block"><span className="mb-2 block text-sm font-medium text-zinc-300">{label}</span><select className="w-full rounded-xl border border-white/10 bg-zinc-950/60 px-4 py-3.5 text-white outline-none transition focus:border-cyan-400/70 focus:ring-4 focus:ring-cyan-400/10" {...props}><option value="">Select</option>{children}</select>{error && <span className="mt-1 block text-xs text-rose-400">{error}</span>}</label> }
