import { ChevronLeft, ChevronRight, Flag, Send } from 'lucide-react'
import { useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import toast from 'react-hot-toast'
import Button from '../components/Button'
import QuestionCard from '../components/QuestionCard'
import Timer from '../components/Timer'
import { questions } from '../utils/demoData'
export default function ExamAttemptPage(){const {id}=useParams(),[current,setCurrent]=useState(0),[answers,setAnswers]=useState({}),navigate=useNavigate();const submit=()=>{toast.success('Exam submitted successfully');navigate(`/result/${id}`)};return <div className="mx-auto max-w-6xl"><header className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-cyan-300">EXAM IN PROGRESS</p><h1 className="mt-1 text-2xl font-bold">Advanced JavaScript</h1></div><span className="rounded-full bg-white/5 px-3 py-1.5 text-sm text-zinc-400">Question {current+1} of {questions.length}</span></header><div className="grid gap-6 lg:grid-cols-[1fr_260px]"><div><div className="mb-5 h-2 overflow-hidden rounded-full bg-white/10"><div style={{width:`${((current+1)/questions.length)*100}%`}} className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-400 transition-all"/></div><QuestionCard question={questions[current]} number={current+1} selected={answers[current]} onSelect={value=>setAnswers({...answers,[current]:value})}/><div className="mt-5 flex justify-between"><Button variant="secondary" disabled={current===0} onClick={()=>setCurrent(current-1)}><ChevronLeft size={17}/>Previous</Button>{current===questions.length-1?<Button onClick={submit}><Send size={16}/>Submit exam</Button>:<Button onClick={()=>setCurrent(current+1)}>Next<ChevronRight size={17}/></Button>}</div></div><aside className="glass h-fit rounded-2xl p-5"><p className="mb-3 text-xs font-semibold tracking-widest text-zinc-400">TIME REMAINING</p><Timer/><p className="mb-3 mt-6 text-xs font-semibold tracking-widest text-zinc-400">QUESTION NAVIGATOR</p><div className="grid grid-cols-5 gap-2">{questions.map((_,i)=><button key={i} onClick={()=>setCurrent(i)} className={`grid aspect-square place-items-center rounded-lg text-sm ${current===i?'bg-cyan-400 text-zinc-950':answers[i]!==undefined?'bg-violet-500/35 text-white':'bg-white/5 text-zinc-400'}`}>{i+1}</button>)}</div><button className="mt-6 flex items-center gap-2 text-sm text-zinc-400"><Flag size={16}/>Flag question</button></aside></div></div>}
