import { ArrowRight, Award, BookOpen, CheckCircle2, Trophy } from 'lucide-react'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import Card from '../components/Card'
import ExamCard from '../components/ExamCard'
import { exams } from '../utils/demoData'
import { useAuth } from '../hooks/useAuth'
const stats=[{label:'Total Exams',value:'18',icon:BookOpen,color:'text-violet-300'},{label:'Completed Exams',value:'12',icon:CheckCircle2,color:'text-cyan-300'},{label:'Average Score',value:'86%',icon:Award,color:'text-amber-300'},{label:'Rank',value:'#24',icon:Trophy,color:'text-fuchsia-300'}]
export default function StudentDashboard(){const {user}=useAuth();return <div className="mx-auto max-w-7xl"><motion.header initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-cyan-300">STUDENT DASHBOARD</p><h1 className="mt-1 text-3xl font-bold">Welcome back 👋 {user?.name?.split(' ')[0]}</h1><p className="mt-2 text-zinc-400">A little progress each day adds up to big results.</p></div><Link to="/exams" className="text-sm font-semibold text-cyan-300 hover:text-cyan-200">Browse all exams <ArrowRight className="inline" size={16}/></Link></motion.header><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({label,value,icon:Icon,color},i)=><motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:i*.06}} key={label}><Card className="p-5"><div className={`mb-6 flex size-10 items-center justify-center rounded-xl bg-white/5 ${color}`}><Icon size={20}/></div><p className="text-3xl font-bold">{value}</p><p className="mt-1 text-sm text-zinc-400">{label}</p></Card></motion.div>)}</section><section className="mt-9"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold">Continue learning</h2><span className="text-sm text-zinc-500">3 available exams</span></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{exams.map(exam=><ExamCard key={exam.id} exam={exam}/>)}</div></section></div>}
