import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { motion } from 'framer-motion'
import { BookOpen, ChevronLeft, ChevronRight, Eye, Grid2X2, List, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import { useDeferredValue, useState } from 'react'
import toast from 'react-hot-toast'
import Button from '../components/Button'
import Card from '../components/Card'
import Modal from '../components/Modal'
import Skeleton from '../components/Skeleton'
import SubjectDetailsModal from '../components/subjects/SubjectDetailsModal'
import SubjectFormModal from '../components/subjects/SubjectFormModal'
import { createSubject, deleteSubject, getSubjects, updateSubject } from '../services/subjects'

const PAGE_SIZE = 12
const formatDate = (value) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(value)) : '—'
const message = (error, fallback) => error.response?.data?.message || fallback

export default function SubjectsPage() {
  const [view, setView] = useState('card'); const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [formSubject, setFormSubject] = useState(undefined); const [detailsId, setDetailsId] = useState(null); const [deleteTarget, setDeleteTarget] = useState(null)
  const deferredSearch = useDeferredValue(search); const queryClient = useQueryClient(); const { data, isPending, isError, refetch } = useQuery({ queryKey: ['subjects', { page, search: deferredSearch }], queryFn: () => getSubjects({ page, limit: PAGE_SIZE, search: deferredSearch || undefined }) }); const invalidate = () => queryClient.invalidateQueries({ queryKey: ['subjects'] })
  const createMutation = useMutation({ mutationFn: createSubject, onSuccess: () => { toast.success('Subject created successfully'); setFormSubject(undefined); invalidate() }, onError: (error) => toast.error(message(error, 'Unable to create subject')) }); const updateMutation = useMutation({ mutationFn: updateSubject, onSuccess: () => { toast.success('Subject updated successfully'); setFormSubject(undefined); invalidate() }, onError: (error) => toast.error(message(error, 'Unable to update subject')) }); const deleteMutation = useMutation({ mutationFn: deleteSubject, onSuccess: () => { toast.success('Subject deleted successfully'); setDeleteTarget(null); invalidate() }, onError: (error) => toast.error(message(error, 'Unable to delete subject')) })
  const subjects = data?.subjects || []; const pagination = data?.pagination; const save = (payload) => formSubject?.id ? updateMutation.mutate({ id: formSubject.id, payload }) : createMutation.mutate(payload)
  return <div className="mx-auto max-w-7xl pb-8"><header className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold tracking-wide text-cyan-300">CURRICULUM MANAGEMENT</p><h1 className="mt-1 text-3xl font-bold tracking-tight sm:text-4xl">Subjects</h1><p className="mt-2 text-sm text-zinc-400 sm:text-base">Organize the subject catalog and its question banks.</p></div><Button onClick={() => setFormSubject({})}><Plus size={18} />Add subject</Button></header><Card className="overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 p-5"><div className="relative w-full max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-500" size={18} /><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1) }} placeholder="Search subjects by name, code, or description" className="w-full rounded-xl border border-white/10 bg-white/[.03] py-2.5 pl-10 pr-4 text-sm text-white outline-none placeholder:text-zinc-500 focus:border-cyan-400/60 focus:ring-4 focus:ring-cyan-400/10" /></div><div className="flex items-center gap-2"><span className="hidden text-sm text-zinc-500 sm:block">{pagination ? `${pagination.total} subjects` : '—'}</span><ViewButton active={view === 'card'} label="Card view" onClick={() => setView('card')}><Grid2X2 size={17} /></ViewButton><ViewButton active={view === 'table'} label="Table view" onClick={() => setView('table')}><List size={18} /></ViewButton></div></div>{isPending ? <Loading view={view} /> : isError ? <Error retry={refetch} /> : subjects.length === 0 ? <Empty search={deferredSearch} add={() => setFormSubject({})} /> : <>{view === 'card' ? <div className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-3">{subjects.map((subject, index) => <SubjectCard key={subject.id} subject={subject} index={index} view={() => setDetailsId(subject.id)} edit={() => setFormSubject(subject)} remove={() => setDeleteTarget(subject)} />)}</div> : <SubjectTable subjects={subjects} view={(id) => setDetailsId(id)} edit={(subject) => setFormSubject(subject)} remove={(subject) => setDeleteTarget(subject)} />}<Pagination pagination={pagination} page={page} setPage={setPage} /></>}</Card><SubjectFormModal open={formSubject !== undefined} subject={formSubject?.id ? formSubject : null} onClose={() => setFormSubject(undefined)} onSubmit={save} isPending={createMutation.isPending || updateMutation.isPending} /><SubjectDetailsModal subjectId={detailsId} onClose={() => setDetailsId(null)} /><DeleteModal subject={deleteTarget} close={() => setDeleteTarget(null)} confirm={() => deleteMutation.mutate(deleteTarget.id)} pending={deleteMutation.isPending} /></div>
}

function SubjectCard({ subject, index, view, edit, remove }) { return <motion.article initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.04 }} whileHover={{ y: -3 }} className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex items-start justify-between gap-3"><span className="grid size-10 place-items-center rounded-xl bg-cyan-400/10 text-cyan-300"><BookOpen size={19} /></span><Status status={subject.status} /></div><h2 className="mt-5 text-lg font-bold">{subject.name}</h2><p className="mt-1 font-mono text-xs text-cyan-200">{subject.code}</p><p className="mt-4 line-clamp-2 min-h-10 text-sm leading-5 text-zinc-400">{subject.description || 'No description provided.'}</p><div className="mt-5 flex items-center justify-between border-t border-white/10 pt-4"><span className="text-sm text-zinc-500">{subject.totalQuestions} questions</span><Actions view={view} edit={edit} remove={remove} /></div></motion.article> }
function SubjectTable({ subjects, view, edit, remove }) { return <div className="overflow-x-auto"><table className="w-full min-w-225 text-left text-sm"><thead className="bg-white/[.025] text-xs uppercase tracking-wider text-zinc-500"><tr>{['Subject', 'Code', 'Description', 'Status', 'Questions', 'Created date', 'Actions'].map((heading) => <th key={heading} className="px-5 py-3 font-medium">{heading}</th>)}</tr></thead><tbody>{subjects.map((subject, index) => <motion.tr key={subject.id} initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.03 }} className="border-t border-white/5"><td className="px-5 py-4 font-medium text-white">{subject.name}</td><td className="px-5 py-4 font-mono text-xs text-cyan-200">{subject.code}</td><td className="max-w-75 truncate px-5 py-4 text-zinc-400">{subject.description || '—'}</td><td className="px-5 py-4"><Status status={subject.status} /></td><td className="px-5 py-4">{subject.totalQuestions}</td><td className="px-5 py-4 text-zinc-400">{formatDate(subject.createdAt)}</td><td className="px-5 py-4"><Actions view={() => view(subject.id)} edit={() => edit(subject)} remove={() => remove(subject)} /></td></motion.tr>)}</tbody></table></div> }
function Actions({ view, edit, remove }) { return <div className="flex gap-1"><IconButton label="View subject" onClick={view}><Eye size={16} /></IconButton><IconButton label="Edit subject" onClick={edit}><Pencil size={16} /></IconButton><IconButton label="Delete subject" danger onClick={remove}><Trash2 size={16} /></IconButton></div> }
function IconButton({ children, label, danger, onClick }) { return <button title={label} aria-label={label} onClick={onClick} className={`rounded-lg p-2 transition ${danger ? 'text-rose-300 hover:bg-rose-500/10' : 'text-zinc-400 hover:bg-white/5 hover:text-cyan-200'}`}>{children}</button> }
function ViewButton({ children, active, label, onClick }) { return <button title={label} aria-label={label} onClick={onClick} className={`rounded-lg p-2 ${active ? 'bg-cyan-400/15 text-cyan-200' : 'text-zinc-500 hover:bg-white/5'}`}>{children}</button> }
function Status({ status }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-medium capitalize ${status === 'active' ? 'bg-emerald-500/10 text-emerald-300' : 'bg-amber-500/10 text-amber-300'}`}>{status}</span> }
function Pagination({ pagination, page, setPage }) { if (!pagination || pagination.totalPages <= 1) return null; return <div className="flex items-center justify-between border-t border-white/10 px-5 py-4"><p className="text-sm text-zinc-500">Page {page} of {pagination.totalPages}</p><div className="flex gap-2"><button disabled={page === 1} onClick={() => setPage(page - 1)} className="rounded-lg border border-white/10 p-2 disabled:opacity-40"><ChevronLeft size={17} /></button><button disabled={page === pagination.totalPages} onClick={() => setPage(page + 1)} className="rounded-lg border border-white/10 p-2 disabled:opacity-40"><ChevronRight size={17} /></button></div></div> }
function Loading({ view }) { return view === 'card' ? <div className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }, (_, index) => <Skeleton key={index} className="h-62" />)}</div> : <div className="space-y-2 p-5">{Array.from({ length: 6 }, (_, index) => <Skeleton key={index} className="h-16" />)}</div> }
function Empty({ search, add }) { return <div className="grid min-h-75 place-items-center p-8 text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-cyan-400/10 text-cyan-300"><BookOpen /></span><h2 className="mt-4 font-bold">{search ? 'No subjects found' : 'No subjects yet'}</h2><p className="mt-2 text-sm text-zinc-500">{search ? 'Try a different search term.' : 'Create the first subject to start building question banks.'}</p>{!search && <Button className="mt-5" onClick={add}><Plus size={16} />Add subject</Button>}</div></div> }
function Error({ retry }) { return <div className="p-8 text-center"><p className="font-medium text-rose-300">Unable to load subjects.</p><button onClick={retry} className="mt-3 text-sm text-cyan-300">Try again</button></div> }
function DeleteModal({ subject, close, confirm, pending }) { return <Modal open={Boolean(subject)} onClose={close} title="Delete subject"><p className="text-sm leading-6 text-zinc-400">Delete <span className="font-medium text-white">{subject?.name}</span>? Subjects already used by questions or exams cannot be deleted.</p><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={close}>Cancel</Button><button onClick={confirm} disabled={pending} className="rounded-xl bg-rose-500 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{pending ? 'Deleting...' : 'Delete subject'}</button></div></Modal> }
