import { UserRound } from 'lucide-react'
import { useForm } from 'react-hook-form'
import toast from 'react-hot-toast'
import Button from '../components/Button'
import Card from '../components/Card'
import { useAuth } from '../hooks/useAuth'
import api from '../services/api'

export default function TeacherProfilePage() { const { user, login } = useAuth(); const { register, handleSubmit, formState: { isSubmitting } } = useForm({ defaultValues: { name: user?.name, email: user?.email, password: '' } }); const save = async (values) => { try { if (!values.password) delete values.password; const { data } = await api.put('/auth/profile', values); login(data, { remember: true }); toast.success('Profile updated') } catch (error) { toast.error(error.response?.data?.message || 'Unable to update profile') } }; return <div className="mx-auto max-w-3xl"><p className="text-sm font-semibold text-cyan-300">ACCOUNT SETTINGS</p><h1 className="mt-1 text-3xl font-bold">Teacher profile</h1><p className="mt-2 text-zinc-400">Update your profile and password.</p><Card className="mt-7 p-6"><div className="flex items-center gap-4"><span className="grid size-14 place-items-center rounded-2xl bg-cyan-400/10 text-cyan-300"><UserRound size={25} /></span><div><p className="text-lg font-bold">{user?.name}</p><p className="capitalize text-zinc-500">{user?.role}</p></div></div><form onSubmit={handleSubmit(save)} className="mt-6 grid gap-4 sm:grid-cols-2"><label><span className="text-sm text-zinc-400">Name</span><input className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.03] p-3 text-white" {...register('name', { required: true })} /></label><label><span className="text-sm text-zinc-400">Email</span><input type="email" className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.03] p-3 text-white" {...register('email', { required: true })} /></label><label className="sm:col-span-2"><span className="text-sm text-zinc-400">New password</span><input type="password" placeholder="Leave blank to keep current password" className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.03] p-3 text-white" {...register('password', { minLength: 8 })} /></label><Button type="submit" disabled={isSubmitting} className="sm:col-span-2">{isSubmitting ? 'Saving...' : 'Save profile'}</Button></form></Card></div> }
