import { useQuery } from '@tanstack/react-query'
import { useEffect } from 'react'
import { useForm } from 'react-hook-form'
import Button from '../Button'
import Input from '../Input'
import Modal from '../Modal'
import { getSubjects } from '../../services/subjects'

const defaults = { subjectId: '', questionText: '', optionA: '', optionB: '', optionC: '', optionD: '', correctAnswer: 'A', marks: 1, difficulty: 'easy', status: 'active' }
const letters = ['A', 'B', 'C', 'D']

const fromQuestion = (question) => ({ subjectId: question.subjectId, questionText: question.questionText, optionA: question.options?.[0]?.optionText || '', optionB: question.options?.[1]?.optionText || '', optionC: question.options?.[2]?.optionText || '', optionD: question.options?.[3]?.optionText || '', correctAnswer: letters[question.options?.findIndex((option) => option.isCorrect)] || 'A', marks: question.marks, difficulty: question.difficulty, status: question.status })

export default function QuestionFormModal({ open, question, onClose, onSubmit, isPending }) {
  const { data: subjectsData } = useQuery({ queryKey: ['subjects', 'form'], queryFn: () => getSubjects({ page: 1, limit: 100 }), enabled: open })
  const { register, handleSubmit, reset, formState: { errors } } = useForm({ defaultValues: defaults })
  useEffect(() => { reset(question ? fromQuestion(question) : defaults) }, [question, open, reset])
  const submit = (values) => onSubmit({ subjectId: Number(values.subjectId), questionText: values.questionText, marks: Number(values.marks), difficulty: values.difficulty, status: values.status, options: letters.map((letter) => ({ optionText: values[`option${letter}`], isCorrect: values.correctAnswer === letter })) })
  return <Modal open={open} onClose={onClose} title={question ? 'Edit question' : 'Add question'}><form onSubmit={handleSubmit(submit)} noValidate className="space-y-4"><label className="block"><span className="mb-2 block text-sm font-medium text-zinc-300">Subject</span><select className="w-full rounded-xl border border-white/10 bg-zinc-950/60 px-4 py-3.5 text-white outline-none focus:border-cyan-400/70" {...register('subjectId', { required: 'Subject is required' })}><option value="">Select a subject</option>{subjectsData?.subjects?.map((subject) => <option key={subject.id} value={subject.id}>{subject.name} ({subject.code})</option>)}</select>{errors.subjectId && <span className="mt-1 block text-xs text-rose-400">{errors.subjectId.message}</span>}</label><label className="block"><span className="mb-2 block text-sm font-medium text-zinc-300">Question text</span><textarea rows="4" className="w-full resize-y rounded-xl border border-white/10 bg-zinc-950/60 px-4 py-3 text-white outline-none focus:border-cyan-400/70" placeholder="Write the question..." {...register('questionText', { required: 'Question text is required' })} />{errors.questionText && <span className="mt-1 block text-xs text-rose-400">{errors.questionText.message}</span>}</label><div className="space-y-3"><p className="text-sm font-medium text-zinc-300">Options and correct answer</p>{letters.map((letter) => <div key={letter} className="flex items-center gap-3"><input type="radio" value={letter} aria-label={`Mark option ${letter} as correct`} className="size-4 accent-cyan-400" {...register('correctAnswer')} /><Input label={`Option ${letter}`} className="flex-1" error={errors[`option${letter}`]?.message} {...register(`option${letter}`, { required: `Option ${letter} is required` })} /></div>)}</div><div className="grid gap-4 sm:grid-cols-3"><Input label="Marks" type="number" min="0.01" step="0.01" error={errors.marks?.message} {...register('marks', { required: 'Marks are required', min: { value: 0.01, message: 'Marks must be greater than zero' } })} /><Select label="Difficulty" {...register('difficulty')}><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></Select><Select label="Status" {...register('status')}><option value="active">Active</option><option value="inactive">Inactive</option></Select></div><div className="flex justify-end gap-3 border-t border-white/10 pt-5"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={isPending}>{isPending ? 'Saving...' : question ? 'Save changes' : 'Create question'}</Button></div></form></Modal>
}
function Select({ label, children, ...props }) { return <label className="block"><span className="mb-2 block text-sm font-medium text-zinc-300">{label}</span><select className="w-full rounded-xl border border-white/10 bg-zinc-950/60 px-4 py-3.5 text-white outline-none focus:border-cyan-400/70" {...props}>{children}</select></label> }
